### ISSUE TITLE
More Projectors Supported - e.g. PT-VX600

### ISSUE THREAD

**Issue by DGoose** [bitfocus/companion-module-panasonic-projector#10]
I have tried using this module on a Panasonic PT-VX600 but it does not work. It will connect but most (all?) commands don't seem to work and many of the projector variables return either blank or "undefined". Is it possible to expand this to work with a greater range of projectors? What can I do here?

**Comment by peschuster** [comment]
Hi,

according to the manual of PT-VX600 (page 110) only a very limited number of commands is supported by this model.
These small models don't have the features required for usage with this companion module specifically designed for the advanced features of the "pro series" panasonic projectors.
I'd suggest using the generic PJ link module to control these basic projectors like e.g. your PT-VX600.
