### ISSUE TITLE
Panasonic Projector Module : Lens Memory Feature request

### ISSUE THREAD

**Issue by Pierreopierre** [bitfocus/companion-module-panasonic-projector#11]
Hi !

I work in a theater environment,
Using two PT-RQ22k from Panasonic.
Module works fine for shutter control and state.

The show requires several lens memory,
I'd like to know if there is a way to recall them from companion.

Thanks

**Comment by milander** [comment]
Just checking if there are any updates to this request. 
I'm looking for this feature too.

**Comment by peschuster** [comment]
Added in latest beta build: https://user.bitfocus.io/builds/companion
