### ISSUE TITLE
Model panasonic rz-970

### ISSUE THREAD

**Issue by mettez** [bitfocus/companion-module-panasonic-projector#26]
We are using companion succesfully with our projector for a couple of years.
We recently upgraded to the latest version of companion.

We now have an issue with the connection. It connects, but every couple of seconds it loses connection, and connects again.
My best guess is that the error occurs because the power of the device is off.

The log file
Starting up module class: 
Sentry disabled
Module-host accepted registration
debug: socket connect
debug: Received change: model -> RZ970
debug: Received change: name -> BEAMERPODIUM
debug: Received change: Power -> false
Starting up module class: 
Sentry disabled
Module-host accepted registration

debug: socket connect
debug: Received change: model -> RZ970
debug: Received change: name -> BEAMERPODIUM
debug: Received change: Power -> false
Starting up module class: 
Sentry disabled
Module-host accepted registration
debug: socket connect
debug: Received change: model -> RZ970
debug: Received change: name -> BEAMERPODIUM
debug: Received change: Power -> false
Starting up module class: 
Sentry disabled
Module-host accepted registration
debug: socket connect
debug: Received change: model -> RZ970
debug: Received change: name -> BEAMERPODIUM
debug: Received change: Power -> false
Starting up module class: 
Sentry disabled
...

A more indepth error report:

[companion error.pdf](https://github.com/bitfocus/companion-module-panasonic-projector/files/11845978/companion.error.pdf)

**Comment by cyberblaststudios** [comment]
The module disconnect issue should be fixed now in companion v3.0.0 stable.
