### ISSUE TITLE
No connection to Panasonic DZ110XE

### ISSUE THREAD

**Issue by airbenich** [bitfocus/companion-module-panasonic-projector#3]
When i try to connect to Panasonic PT DZ110XE the following data occurs in the log file:
User and PW are placed in module settings and correct.
Any idea on this?

`08. 18:42:13 instance(Beamer Dachboden Panasonic): Unkown data received: ERR1
08. 18:42:13 instance(Beamer Dachboden Panasonic): socket connect`

**Comment by peschuster** [comment]
What port are you using? NTCONTROL is set to 1024 by default. Not sure whether that can be changed in the projector configuration.
Are any variables filled? (at the bottom of the configuration page of the instance)
What is the connection status on the overview page with all instances?

**Comment by airbenich** [comment]
In the user manual port 1024 is also mentioned for this projector as default port. It wasn't changed as far as i know. 

The connection status is OK.

The dynamic variables are:


Variable | Description | Current value
-- | -- | --
$(projector:name) | Name |  
$(projector:model) | Model |  
$(projector:power) | Power state | undefined
$(projector:shutter) | Shutter state | undefined
$(projector:freeze) | Freeze state | undefined
$(projector:input) | Input |  
$(projector:lamp_state) | Lamp state | undefined
$(projector:brightness) | Brightness | 100
$(projector:test_pattern) | Test Pattern |  
$(projector:color_matching) | Color Matching Mode | undefined
$(projector:color_matching_3c_red) | Color Matching 3-Colors: Red | 2048,0,0
$(projector:color_matching_3c_green) | Color Matching 3-Colors: Green | 0,2048,0
$(projector:color_matching_3c_blue) | Color Matching 3-Colors: Blue | 0,0,2048
$(projector:color_matching_7c_red) | Color Matching 7-Colors: Red | 2048,0,0
$(projector:color_matching_7c_green) | Color Matching 7-Colors: Green | 0,2048,0
$(projector:color_matching_7c_blue) | Color Matching 7-Colors: Blue | 0,0,2048
$(projector:color_matching_7c_cyan) | Color Matching 7-Colors: Cyan | 0,2048,2048
$(projector:color_matching_7c_magenta) | Color Matching 7-Colors: Magenta | 2048,0,2048
$(projector:color_matching_7c_yellow) | Color Matching 7-Colors: Yellow | 2048,2048,0
$(projector:color_matching_7c_white) | Color Matching 7-Colors: White | 2048,2048,2048

**Comment by peschuster** [comment]
It looks like the connection was successful and authentication worked, but the projector rejects the sent commands and does not answer with a known header prefix.
Does it work with the [Geometry Manager](https://www.dropbox.com/s/e2dvz0recnfl3ke/Geometry%20manager%20Pro%205.3.18.zip?dl=1) tool by Panasonic? 
Do you have the ability to create a Wireshark capture of the communication?

**Comment by airbenich** [comment]
Geometry manager can't connect to the projector: Failed to connect [100020]
I will install wireshark at post the communication shortly.

**Comment by airbenich** [comment]
Which file format would be good for the dump?

**Comment by airbenich** [comment]
Wireshark dump filtered to Projector IP:
https://we.tl/t-YUZCdhL2Zl

**Comment by peschuster** [comment]
Thanks.
The projector does not seem to understand the command and closes the connection.
This module uses a slight variation/extension of the protocol which is also used by the Geometry Manager tool.
I will probably need to add a compatibility mode which only uses the basic command format, but this might take a few days.

**Comment by airbenich** [comment]
Okay! That would be awesome to have in this module! Happy easter! :)
