### ISSUE TITLE
v3 release - Feedbacks broken

### ISSUE THREAD

**Issue by VideoBSO** [bitfocus/companion-module-panasonic-projector#30]
Since the release of v3 feedbacks are broken as the variable is set to the returned `bool` value and not mapped to `choiceOnOff`.

Connection, sending commands to the projector and receiving responses in general all work flawless, just the handling of the returned values seems broken.

~~I wanted to have a look if I can fix it with a local clone of the module, but I can't get it to run from the local clone (actually none so I guess I somehow broke my dev env).~~ Never mind, I was missing the deps `npm install` ftw.

**Comment by VideoBSO** [comment]
I tried this and now `$(projector-name:shutter` looks correct, but the feedback is still not working:
```diff
diff --git a/index.js b/index.js
index a7844a4..a5bb291 100644
--- a/index.js
+++ b/index.js
@@ -531,7 +531,11 @@ class PanasonicInstance extends InstanceBase {
                                this.checkFeedbacks(Constants.Freeze)
                                break
                        case 'Shutter':
-                               this.setVariableValues({ [Constants.Shutter]: value })
+                               if (value) {
+                                                       this.setVariableValues({ [Constants.Shutter]: Constants.On })
+                               } else  {
+                                                       this.setVariableValues({ [Constants.Shutter]: Constants.Off })
+                               }
                                this.checkFeedbacks(Constants.Shutter)
                                break
                        case 'InputSelect':
```

**Comment by dnmeid** [comment]
I have no projector here to test, but I hope I fixed the problem. Please check with the attached package and report back if that worked, so I can release it.
[pkg.tgz](https://github.com/bitfocus/companion-module-panasonic-projector/files/12083843/pkg.tgz)

**Comment by VideoBSO** [comment]
Ok, I can confirm most feedbacks now.
The only one I can not get the correct feedback from the projector {so this might be a compatibility issue actually) is `freeze` where the variable doesn't change.
The other that does not work for all our projectors is `input` as our RQ22 use option Boards which report them selves oddly. For example the HDMI1 of Slot 2 reports it self as `AU2,HD3` or for DVI2 in Slot 1 `AU1,DV2`.

**Comment by dnmeid** [comment]
The module uses the external library https://github.com/peschuster/ntcontrol-connection for the communication to the projectos. The naming of Inputs is reportet by that library.
It has not been updated for three years, maybe Panasonic did some changes in newer firmwares which are not supported by ntcontrol-connection.
Feel free to file a bug there.

So if the feedbacks are now working in general, I do release this version.

**Comment by VideoBSO** [comment]
But did you see [my comment](https://github.com/bitfocus/companion-module-panasonic-projector/commit/4e69ba34c545fc6b3e5949a3f7a7e698c6728af4#r121999457) on commit 
4e69ba3?

I will try to report the misinterpreted inputs upstream. The projectors actually are older then 3 years and are by now actually replaced by their predecessor RQ25, just fyi..

**Comment by dnmeid** [comment]
@VideoBSO I fixed the on/off feedbacks according to your diff. Can you please check again and report if everything is working.

**Comment by VideoBSO** [comment]
Thanks. I can check and report back tomorrow, today the projectors are not accessible.

**Comment by VideoBSO** [comment]
Thanks again @dnmeid, all working now!

**Comment by dnmeid** [comment]
Good to hear.
@VideoBSO Wenn ich das nächste mal in München bin, kann ich euch ja mal besuchen kommen.

**Comment by VideoBSO** [comment]
> Good to hear. @VideoBSO Wenn ich das nächste mal in München bin, kann ich euch ja mal besuchen kommen.

Sehr gerne, jederzeit willkommen. Am besten einfach auf der video@staatsoper.de kurz durchklingeln..
