### ISSUE TITLE
No feedback display with RZ120 and RZ31K

### ISSUE THREAD

**Issue by yrphilippe** [bitfocus/companion-module-panasonic-projector#37]
Hello,
and thanks for this very useful module.
However, I have a problem with this one.
I'm using two RZ120 projectors and one RZ31K and I want to control the shutters and freeze function.
Using the SHUTTER TOGGLE and FREEZE TOGGLE presets, I can activate/deactivate the shutters and freeze, but feedback doesn't seem to work, whereas in debug mode I can see the response: Received change: Shutter -> true
Any advice?
Yann

**Comment by peschuster** [comment]
I noticed that feedback in presets is broken.
I.e. it only affects buttons created through presets, but not the actual feedback function.

You can fix this by editing the feedback on the buttons and manually configuring the fore and background colors for the feedback.
Let me know if this fixes your issue.

**Comment by peschuster** [comment]
Fixed in latest beta build: https://user.bitfocus.io/builds/companion

**Comment by yrphilippe** [comment]
Thank you ! 
I don't have the projectors to test, but I'll do it as soon as possible.
