### ISSUE TITLE
Panasonic PT-VMW50 Unkown data received: ERR1

### ISSUE THREAD

**Issue by pblosser03** [bitfocus/companion-module-panasonic-projector#4]
Trying to setup a PT-VMW50U with the name Rear Projector.  Already setup a PT-M770LBU as Front Projector and it works wonderfully. But the PT-VMW50U keeps giving errors and will not respond to commands. Any help in getting this working would be much appreciated!

18. 18:08:41 instance(Rear Projector): Unkown data received: ERR1
18. 18:08:41 instance(Rear Projector): socket connect
...
18. 17:56:28 instance(Rear Projector): Unkown data received: ERR1
18. 17:56:28 instance(Rear Projector): socket connect
18. 17:56:26 instance(Rear Projector): Unkown data received: ERR1
18. 17:56:26 instance(Rear Projector): socket connect
18. 17:56:26 instance(wu7l5sUVs): instance configuration updated
18. 17:56:02 instance(wu7l5sUVs): instance add panasonic-projector Projector

**Comment by pblosser03** [comment]
![ProjectorInstances](https://user-images.githubusercontent.com/69877131/90574482-a8107080-e17e-11ea-8c9e-4bd24e6c3ca8.PNG)

**Comment by pblosser03** [comment]
Projector control port is set to 1024 and is also set to the same in companion.  I did not change either.

![ProjectorControlPort](https://user-images.githubusercontent.com/69877131/90574716-3c7ad300-e17f-11ea-80a7-640dfe52bfe9.PNG)

**Comment by pblosser03** [comment]
Packet capture of communication with projector. Let me know if you need anything more specific.

[PanasonicCapture.pcapng.gz](https://github.com/bitfocus/companion-module-panasonic-projector/files/5093322/PanasonicCapture.pcapng.gz)

**Comment by peschuster** [comment]
Thanks for your feedback.
I had a look at your packet capture and can confirm that it is the same issue as in #3 

This companion module implements the NTCONTROL protocol in a variant as used by the "Panasonic Geometry Manager" tool. But this variant of the protocol only seems to be supported by larger models.
I have an idea how to also support smaller projectors using only a subset of the commands, but this requires a rewrite of the connection management, which I have not found time for, yet. 
But it is on my schedule and I will make time for it in the upcoming weeks.

**Comment by pblosser03** [comment]
Awesome, thanks for all your hard work.

**Comment by tryonrobotics** [comment]
Thank you peschuster for your time putting all of this together.
I have a PT-VMZ60U and am seeing the same as pblosser03 above.

I am temporarily leaving projector control out of my Companion interface, however would love to add it in if this project comes back on your radar.  I can control it via web interface, it does connect to companion and variables show up, however Geometry Manager cannot connect to the projector, nor do the companion presets do anything.

thanks again for your time on this.  Can I send beer money?  ha!

**Comment by redmug** [comment]
Hi peschuster, thanks for all of your work on this! I am also facing this issue when trying to connect to PT-VW600. 

21. 01:04:21 instance(projector): Unkown data received: ERR1
21. 01:04:21 instance(projector): socket connect

**Comment by austgresh** [comment]
Hi Peschuster, 
I am also experiencing the same issue with the "closed socket" with a PT-VMZ60u.  I have several of these projectors and would like to be able to toggle them on/off with Companion and a streamdeck on Raspberry Pi so that I can avoid using Crestron.

**Comment by peschuster** [comment]
For simple commands / use cases I'd recommend using the generic pjlink module. The special panasonic control protocol is only required to change color temperatures, test patterns, etc.

**Comment by redmug** [comment]
Hi Peter,

The pjlink module is working fine for me and does everything I require.

Thank you.
Marcus
