### ISSUE TITLE
Cannot Select HDMI2 as Input for Panasonic VZ580 Projector

### ISSUE THREAD

**Issue by enochchan** [bitfocus/companion-module-panasonic-projector#5]
I was trying to use this module with the **"Panasonic VZ580"** projector.   There was no option to select **HDMI 2** as input that should be available on the projector.  On the other hand, the 8th button on the first row (see attached screenshot) was able to report that the active input being used was **"HD2"** (when HDMI 2 is manual selected).

I had also tried the other available inputs, such as DVI, SDI, etc., in the module but without success.

<img width="1680" alt="Screenshot 2020-11-08 at 10 57 57 AM" src="https://user-images.githubusercontent.com/7971225/98467613-4d346580-2211-11eb-9d7f-d47fd06aa38d.png">

Thanks in advance for the help!

**Comment by peschuster** [comment]
Unfortunately this module still only works with the large venue Panasonic projectors which are supported by the Panasonic tool "Geometry Manager Pro" (mostly the PT-D/R* line of projectors). These projectors implement a more complex "flavor" of the NT CONTROL protocol.

One of the major differences is that the other projectors don't support long running connections and therefore the connection/state handling inside of this module needs to be changed. I have a draft for that, but not yet a solution to handle both variants of this protocol in one module and a mechanism to detect which type to use.

**Comment by enochchan** [comment]
Thank you for the reply!  The current module **does work** in our situation such as "mute" or "unmute" the Panasonic projector, as well as obtaining feedback such as if the project is "Powered On".  

The issue that I was having is that the option to select "**HDMI2**" as input in the project is not available for selection.

I did a bit of reading of the code and noted that this module is also referring to your "**ntcontrol-connection**" library; 

I was wondering if that issue could be related to the file "**Types.ts**" (https://github.com/peschuster/ntcontrol-connection/blob/master/src/Types.ts) in that library, and if adding a line say "**HDMI2 = 'HD2'**" to the following section in "**Types.ts**" might help resolve the missing input:

```
export enum ProjectorInput {
    COMPUTER1 = 'RG1',
    COMPUTER2 = 'RG2',
    VIDEO = 'VID',
    'Y/C' = 'SVD',
    DVI = 'DVI',
    HDMI1 = 'HD1',
    SDI1 = 'SD1',
    SDI2 = 'SD2',
    'DIGITAL LINK' = 'DL1'
}
```

Of course, I am not knowledgeable enough to know if other part(s) of the code might need to be modified as well.

Thanks again for the feedback!

**Comment by peschuster** [comment]
Support for the input types of this projector were added to the module and are now part of the nightly builds ready for testing: https://bitfocus.io/companion/download/builds/
