### ISSUE TITLE
No Connection Companion to Panasonic PT-VMZ60U

### ISSUE THREAD

**Issue by austgresh** [bitfocus/companion-module-panasonic-projector#6]
Very new to programming and everything.  Trying to learn.

Goal - to use a Stream Deck connected to Companion Pi to control a Panasonic PT-VMZ60U projector (mainly to turn on and off since it will be mounted out of reach).

Installed Panasonic Projector instance in Companion but it will not talk to the projector.  Manually inputted IP address in both projector and Companion Config page.  Made a simple button to display the test pattern and nothing happens.  The Companion log shows "no connection available".  

Is this a case of the model of the projector not being compatible or something else?

**Comment by peschuster** [comment]
It might be the case that this specific model does not support the advanced NT CONTROL protocol.
If all you are looking for is switching the projector on and off you can also use the generic pjlink module in companion.

**Comment by austgresh** [comment]
Thanks. While pjlink doesn't have all the options of the other module it does all that I need and works great!
