### ISSUE TITLE
DZ21k2 no color feedback on the Status Lamp

### ISSUE THREAD

**Issue by DiegoMarchente** [bitfocus/companion-module-panasonic-projector#8]
I'm using Companion 2.2.1 and the Panasonic Projector module to manage 4 projectors DZ21K2. My current problem lies in the Feedback of the Status Lamp, which work perfectly in the switching on, off, cooling and warm-up phases for the text writings, but the background colors do not activate in any way.

![Immagine 2022-06-03 081900](https://user-images.githubusercontent.com/50266654/171987340-f18a7f59-0b1a-403b-ba01-b475dee20181.png)

**Comment by peschuster** [comment]
Thanks for the feedback. I can reproduce this issue and am looking into it.

**Comment by peschuster** [comment]
The issue is fixed and a new beta build of companion is available here: https://bitfocus.io/companion/download/builds/
